// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PessoasAptas.Infrastructure.Persistence;

namespace PessoasAptas.Infrastructure.Migrations
{
    [DbContext(typeof(BeneficioGovernoDbContext))]
    partial class BeneficioGovernoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PessoasAptas.Core.Entities.Criterio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Criterios");
                });

            modelBuilder.Entity("PessoasAptas.Core.Entities.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("PessoasAptas.Core.Entities.PessoaCriterio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdCriterio")
                        .HasColumnType("int");

                    b.Property<int>("IdPessoa")
                        .HasColumnType("int");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCriterio");

                    b.HasIndex("IdPessoa");

                    b.ToTable("PessoaCriterios");
                });

            modelBuilder.Entity("PessoasAptas.Core.Entities.PessoaCriterio", b =>
                {
                    b.HasOne("PessoasAptas.Core.Entities.Criterio", "Criterio")
                        .WithMany("PessoaCriterios")
                        .HasForeignKey("IdCriterio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PessoasAptas.Core.Entities.Pessoa", "Pessoa")
                        .WithMany("PessoaCriterios")
                        .HasForeignKey("IdPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criterio");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("PessoasAptas.Core.Entities.Criterio", b =>
                {
                    b.Navigation("PessoaCriterios");
                });

            modelBuilder.Entity("PessoasAptas.Core.Entities.Pessoa", b =>
                {
                    b.Navigation("PessoaCriterios");
                });
#pragma warning restore 612, 618
        }
    }
}
